//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateMaster
    {
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public string CandidateEmailId { get; set; }
        public string MarketingEmailId { get; set; }
        public string ContactNumber { get; set; }
        public string MarketingNumver { get; set; }
        public string InsertBy { get; set; }
        public string Technology { get; set; }
    }
}
