//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbReportingSystemEntities : DbContext
    {
        public dbReportingSystemEntities()
            : base("name=dbReportingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandidateMaster> CandidateMasters { get; set; }
        public virtual DbSet<InterviewMaster> InterviewMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<TeamMaster> TeamMasters { get; set; }
        public virtual DbSet<TechnologyMaster> TechnologyMasters { get; set; }
        public virtual DbSet<UserLoginMaster> UserLoginMasters { get; set; }
        public virtual DbSet<JobPortalMaster> JobPortalMasters { get; set; }
        public virtual DbSet<SubmissionMaster> SubmissionMasters { get; set; }
    }
}
