//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewMaster
    {
        public int IId { get; set; }
        public System.DateTime IDate { get; set; }
        public System.TimeSpan ITime { get; set; }
        public string Description { get; set; }
        public int RefSId { get; set; }
        public string Status { get; set; }
        public string AssignTo { get; set; }
        public string FeedBack { get; set; }
    
        public virtual SubmissionMaster SubmissionMaster { get; set; }
    }
}
