//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTRS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmissionMaster()
        {
            this.InterviewMasters = new HashSet<InterviewMaster>();
        }
    
        public int SId { get; set; }
        public System.DateTime SDate { get; set; }
        public System.TimeSpan STime { get; set; }
        public string SBy { get; set; }
        public string CandidateName { get; set; }
        public string Technology { get; set; }
        public string Location { get; set; }
        public decimal Rate { get; set; }
        public string ClientName { get; set; }
        public string VendorName { get; set; }
        public string ContactEmailId { get; set; }
        public string VendorCompanyName { get; set; }
        public string JobPortalName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterviewMaster> InterviewMasters { get; set; }
    }
}
